name: Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: codespace
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /workspaces/dockerized-app
            git pull
            docker compose down
            docker compose up -d --build